version: '2'
services:
    readword-app:
        image: readword
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://readword-mysql:3306/readword?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=readword-elasticsearch:9300
        ports:
            - 8080:8080
    readword-mysql:
        extends:
            file: mysql.yml
            service: readword-mysql
    readword-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: readword-elasticsearch
